### ISSUE TITLE
kein Unentschieden

### ISSUE THREAD

**Issue by maxdavidguenther** [LentiCularier/TicTacToe-mit-Bots-und-Arrays2#2]
TicTacToe kann auch unentschieden ausgehen, ist aber nicht vorgesehen.

**Comment by LentiCularier** [comment]
> TicTacToe kann auch unentschieden ausgehen, ist aber nicht vorgesehen.

hmm... Eigentlich hab ich das schon beachtet. 
Die Funktion "EndeOhneSiegUeberpruefung" schaut  nach jedem Zug, ob die Spielzuganzahl nicht bereits 9 beträgt und führt je nachdem dann dem entsprechend die Funktion "EndeOhneSieg" (enthält hauptsächlich nur Text für die Konsole) aus.

Oder funktioniert das aktuell nicht?
